name: RTSP
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cairo=1.18.2
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - double-conversion=3.3.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - glib=2.82.2
  - glib-tools=2.82.2
  - graphite2=1.3.13
  - gstreamer=1.24.7
  - h2=4.1.0
  - harfbuzz=10.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - intel-openmp=2025.0.0
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.5
  - libdeflate=1.22
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgirepository=1.82.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libpng=1.6.44
  - libsqlite=3.47.2
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - mkl=2020.4
  - munkres=1.1.4
  - numpy=2.2.0
  - openjpeg=2.5.3
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pcre2=10.44
  - pip=24.3.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - py-cpuinfo=9.0.0
  - pycairo=1.27.0
  - pycparser=2.22
  - pygobject=3.50.0
  - pyparsing=3.2.0
  - pyside6=6.8.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.8.1
  - requests=2.32.3
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.6.0
  - six=1.17.0
  - statsmodels=0.14.4
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - coloredlogs==15.0.1
      - dill==0.3.9
      - filelock==3.13.1
      - flatbuffers==25.2.10
      - fsspec==2024.2.0
      - humanfriendly==10.0
      - imageio==2.37.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - lapx==0.5.11.post1
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - nats-py==2.9.0
      - networkx==3.2.1
      - onnx==1.18.0
      - onnxruntime==1.22.0
      - opencv-python==4.10.0.84
      - pillow==10.2.0
      - protobuf==6.31.0
      - psutil==6.1.0
      - pyproj==3.7.1
      - pyreadline3==3.5.4
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - sympy==1.13.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - typing-extensions==4.9.0
      - utils==1.0.2